site_name: Soft Robotics Developer Manual

repo_name: roboticslab-uc3m/soft-robotics-developer-manual
repo_url: https://github.com/roboticslab-uc3m/soft-robotics-developer-manual
edit_uri: blob/master/docs/

theme:
  name: material
  language: en
  logo: fig/roboticslab.svg
  favicon: fig/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light-blue
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light-blue
      accent: light-blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra:
  social:
    - icon: material/web
      link: http://roboticslab.uc3m.es/
    - icon: fontawesome/brands/github
      link: https://github.com/roboticslab-uc3m
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/uc3mRoboticsLab
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@RoboticsLabUC3M

exclude_docs: |
  fig/README.md
  fig/editable/README.md

nav:
- Home: README.md
#- Cognitive Architecture: architecture.md
- Soft Neck:
  - softneck/README.md
  - Demo-Space Navigator: softneck/demo.md
- Soft Gripper:
  - softgripper/README.md
  - Demo: softgripper/demo.md
  - ElectroMechanical Data: softgripper/motors.md
- Origami:
  - origami/README.md
  - Demo: origami/demo.md
- Roberto:
  - roberto/README.md
  - Demo: roberto/demo.md
- Instron:
  - instron/README.md
  - Demo: instron/demo.md
- MOCAP:
  - mocap/README.md
  - Demo: mocap/demo.md
# - diagrams.md
# - tables.md
# - dynamic-information.md
# - switches-and-power.md
# - connectors.md
# - network-information.md
# - driver-check-procedure.md
# - demo-procedure.md
# - additional-resources.md
# - contributors.md

use_directory_urls: false

markdown_extensions:
  - attr_list # for mkdocs-pdf
  - toc:
      permalink: '#'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - open-in-new-tab
  - git-revision-date-localized
  - table-reader
  - include-markdown
  - mermaid2
  - mkdocs-pdf
  - autorefs
